Error messaging in tera_fn
_This is a follow up to https://github.com/getzola/zola/pull/1036_

I wanted it to be a bit easier to identify that this error had come
from a specific function, and instead of adding that information to the
load_data function itself, wanted to investigate how errors were
reported in the first place.

```
Error: Failed to render page '/Users/stanistan/dev/stanistan.com/content/invoice/01.md'
Reason: Failed to render 'invoice.html'
>>> Reason: Failed in tera function call to `load_data` <<< NEW
Reason: Could not get response status for url: http://localhost:3000/invoice/01
```

---

This PR adds information to _every_ `global_fn` registered in tera by the zola.

The approach I've taken is:

1. create a `NamedTeraFn` trait which then means the `tera::Function` can have
   a statically associated name, the `site` no longer has to know the
   name of the function it is registering.
2. Wrap a `tera::Function` in another `tera::Function` which adds this
   name to any error that might have been produced, this is the
   `WrappedTeraFn`.
3. The functions are registered with a `register!` macro, which DRYs up
   those calls a bit.